#!/bin/sh
# TC commands need the 'tc-' prefix in bash.
# (tc-alias.sh is expected to be in the PATH)
. tc-alias.sh

param load
param set CBRK_SUPPLY_CHK 894281

dataman start

tone_alarm start

ver all

sleep 1

tests all

shutdown
