#!/bin/sh
#
# @name TCVision SITL
# Holybro tcvision. Gazebo Only.
#
# @type Quadrotor
#

. ${R}etc/init.d/airframes/4016_holybro_tcvision

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

